config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :storage_items, :except => [:show]

resources :storage_tasks, :only => [:index]

app/models/storage_item.rb
class StorageItem < ActiveRecord::Base
  attr_accessible :name, :cost, :count, :production_time

  belongs_to :issue

  validates :issue_id, :presence => true
  validates :name, :presence => true
  validate :name_unique_for_project
  validate :cost_is_positive
  validate :count_is_positive

  scope :name_like, lambda {|name|
    pattern = "%#{name}%"
    where("LOWER(#{table_name}.name) LIKE LOWER(?)", pattern)
  }

  def name_unique_for_project
    project = issue.try(:project)
    if project
      table_name = self.class.table_name
      if item = self.class.joins(:issue).where("issues.project_id" => project.id, "#{table_name}.name" => name).first
        if item.id != self.id
          errors.add(:name, :must_be_unique)
        end
      end
    end
  end

  def cost_is_positive
    if cost.present?
      if not cost >= 0
        errors.add(:cost, :must_be_positive)
      end
    end
  end

  def count_is_positive
    if count.present?
      if not count >= 0
        errors.add(:count, :must_be_positive)
      end
    end
  end
end

app/controllers/storage_items_controller.rb
class StorageItemsController < ApplicationController
  unloadable

  before_filter :find_project, :only => [:index, :new]
  before_filter :find_item_and_project, :only => [:edit, :update, :destroy]
  before_filter :find_project_by_item_params, :only => [:create]
  before_filter :authorize, :only => [:index, :edit, :new, :create, :update, :destroy]

  helper :sort
  include SortHelper


  def index
    sort_init 'name', 'asc'
    sort_update %w(name cost count production_time)

    scope = StorageItem.joins(:issue => [:project]).where("projects.id" => @project.id)
    scope = scope.name_like(params[:name]) if params[:name].present?
    @items = scope.order(sort_clause)
  end

  def edit
    @project = @item.issue.try(:project)
  end

  def new
    @item = StorageItem.new
  end

  def create
    @item = StorageItem.new params[:storage_item]
    issue = Issue.find params[:storage_item][:issue_id]
    @item.issue = issue
    @project = issue.project
    if @item.save
      redirect_to(storage_items_path(:project_id => @project.id))
    else
      render "new"
    end
  end

  def update
    item_params = params[:storage_item]
    issue = Issue.find item_params[:issue_id] if item_params[:issue_id]
    @project = issue.try(:project) || @item.issue.try(:project)
    if @item.update_attributes item_params
      redirect_to(storage_items_path(:project_id => @project.id))
    else
      render "edit"
    end
  end

  def destroy
    @project = @item.issue.try(:project)
    redirect_params = {:project_id => @project.id} if @project
    if not @item.destroy
      flash[:notice] = l(:notice_can_t_delete_item)
    end
    redirect_to(storage_items_path(redirect_params))
  end

  protected

  def find_project
    @project = Project.find params[:project_id]
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_item_and_project
    @item = StorageItem.find params[:id]
    @project = @item.issue.try(:project)
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_project_by_item_params
    item_params = params[:storage_item]
    issue = Issue.find item_params[:issue_id]
    @project = issue.try(:project)
  end
end

app/controllers/storage_tasks_controller.rb
class StorageTasksController < ApplicationController
  def index
    @project = Project.find params[:project_id]
  end
end

app/helpers/storage_items_helper.rb
module StorageItemsHelper
end

app/views/storage_items/_form.html.erb
<div class="splitcontentleft">
  <%= error_messages_for @item %>
  <fieldset class="box tabular">
    <legend><%= l(:label_create_storage_item) %></legend>
    <p><%= f.text_field :name %> </p>
    <p><%= f.text_field :cost %> </p>
    <p><%= f.text_field :count %> </p>
    <p><%= f.text_field :production_time %>
      <%= calendar_for('storage_item_production_time') %> </p>
    <p><%= f.collection_select :issue_id, @project.issues, :id, :subject %> </p>
    <p><%= f.submit %> </p>
  </fieldset>
</div>

app/views/storage_items/_issue_description_hook.html.erb
<% if authorize_for :storage_items, :index %>
<hr/>

<strong><%= l(:label_storage_item_plural) %> </strong>

<% items = StorageItem.where(:issue_id => @issue.id).all %>
<% if items.count > 0 %>
<div class="autoscroll">
  <table class="list">
    <thead>
      <tr>
        <th><%= l(:field_name) %></th>
        <th><%= l(:field_cost) %></th>
        <th><%= l(:field_count) %></th>
        <th><%= l(:field_production_time) %></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= render :partial => "storage_items/items_table_body", :locals => {:items => items} %>
    </tbody>
  </table>
</div>
<% else %>
  <div>
    <%= l(:label_there_is_no_storage_items) %>
  </div>
<% end %>
<% end %>

app/views/storage_items/_items_table.html.erb
<div class="autoscroll">
  <table class="list">
    <thead>
      <tr>
        <%= sort_header_tag('name', :caption => l(:field_name)) %>
        <%= sort_header_tag('cost', :caption => l(:field_cost)) %>
        <%= sort_header_tag('count', :caption => l(:field_count)) %>
        <%= sort_header_tag('production_time', :caption => l(:field_production_time)) %>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= render :partial => "storage_items/items_table_body", :locals => {:items => items} %>
    </tbody>
  </table>
</div>

app/views/storage_items/_items_table_body.html.erb
<% items.each do |item| %>
  <%= content_tag :tr, :class => cycle('odd', 'even') do %>
    <% if authorize_for :storage_items, :update %>
      <td><%= link_to item.name, edit_storage_item_path(item) %></td>
    <% else %>
      <td><%= item.name %></td>
    <% end %>
    <td><%= item.cost %></td>
    <td><%= item.count %></td>
    <td><%= format_time(item.production_time)%></td>
    <% if authorize_for :storage_items, :destroy %>
      <td><%= delete_link item %> </td>
    <% end %>
  <% end %>
<% end %>

app/views/storage_items/edit.html.erb
<%= title [l(:label_storage_item_plural), storage_items_path], @item.name %>

<%= labelled_form_for @item do |f| %>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end %>

app/views/storage_items/index.html.erb
<% if authorize_for(:storage_items, :create) %>
  <div class="contextual">
    <%= link_to l(:label_storage_item_new), new_storage_item_path(:project_id => @project.id), :class => 'icon icon-add' %>
  </div>
<% end %>

<%= title l(:label_storage_item_plural) %>
&nbsp;

<%= form_tag(storage_items_path, :method => :get) do %>
  <fieldset>
    <legend><%= l(:label_filter_plural) %></legend>
    <%= hidden_field_tag 'project_id', @project.id %>
    <label for="name"><%= l(:field_name) %></label>
    <%= text_field_tag 'name', params[:name], :size => 30 %>
    <%= submit_tag l(:button_apply), :class => 'small', :name => nil %>
    <%= link_to l(:button_clear), storage_items_path(:project_id => @project.id), :class => 'icon icon-reload' %>
  </fieldset>
<% end %>

<%= render :partial => "items_table", :locals => {:items => @items} %>

app/views/storage_items/new.html.erb
<%= title [l(:label_storage_item_plural), storage_items_path], l(:label_storage_item_new) %>

<%= labelled_form_for @item do |f| %>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end %>

app/views/storage_tasks/_tasks_table.html.erb
<table class="list" rules="all">
  <tbody>
    <% 7.times do %>
      <tr><td>
          <table class="storage-task">
            <colgroup>
              <col width="10" />
              <col />
              <col width="100%" />
            </colgroup>
            <tbody>
              <tr class="bold-font">
                <td>
                  <input type="checkbox">
                </td>
                <td>
                  Перезвонить по важному вопросу
                </td>
                <td></td>
                <td rowspan="2">
                  <img src="/plugin_assets/storage/images/user.png" class="user-picture">
                </td>
                <td>
                  Иванов Иван Иванович
                </td>
              </tr>
              <tr>
                <td></td>
                <td>
                  Сегодня 14:00
                </td>
                <td>
                  <div class="force-center">
                    Тип задачи
                  </div>
                </td>
                <td>
                  ООО "Ромашка"
                </td>
              </tr>
              <tr>
                <td></td>
                <td>
                  <div class="label">
                    Метка 1
                  </div>
                  <div class="label-active">
                    Вторая метка
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
      </td></tr>
    <% end %>
  </tbody>
</table>

app/views/storage_tasks/index.html.erb
<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'storage_tasks', :plugin => 'storage' %>
<% end %>


<div class="contextual">
  <%= link_to 'Новая задача', request.original_url, :class => 'icon icon-add' %>
</div>

<h2>Задачи</h2>

<%= render "tasks_table" %>

<% content_for :sidebar do %>
  <h3>Heading 3</h3>
  <% 3.times do %>
    <div>
      <%= link_to 'This is a link. A text link', request.original_url %>
    </div>
  <% end %>
<% end %>